language: c
script: mkdir build && cd build && cmake .. && make && ./duskc ../examples/main.ds
matrix:
  include:
    - os: osx
      osx_image: xcode10
      before_install:
        - eval brew install gcc && CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: xenial
      compiler:
        - gcc
    - os: linux
      dist: xenial
      compiler:
        - clang

