language: cpp
script: mkdir build && cd build && cmake .. && make && make test
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
