language: c
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - cmake
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - llvm
      env:
        - MATRIX_EVAL="LDFLAGS="-L/usr/local/opt/llvm/lib" CPPFLAGS="-I/usr/local/opt/llvm/include" && LLVM_DIR=/usr/local/Cellar/llvm/7.0.0/lib/cmake/llvm && ls -R /usr/local/Cellar/llvm/7.0.0/lib/cmake/; ls /usr/local/Cellar/llvm/"
before_script:
  - eval "${MATRIX_EVAL}"
script: mkdir build && cd build && cmake .. && make && make test
