language: c
script: mkdir build && cd build && cmake .. && make && ./duskc ../examples/main.ds
matrix:
  include:
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: xenial
      compiler:
        - gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=gcc-7"
    - os: linux
      dist: xenial
      compiler:
        - clang
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
before_install:
  - eval "${MATRIX_EVAL}"
