language: c
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - cmake
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm && export LLVM_DIR=/usr/local/Cellar/llvm/3.9.0/lib/cmake"
before_script:
  - eval "${MATRIX_EVAL}"
script: mkdir build && cd build && cmake .. && make && make test
